/**
 * Server-only crypto helpers for signing stream tokens.
 * These ensure the stream API route can only be called with
 * tokens generated by our server — prevents URL tampering.
 */
import crypto from "crypto";

const SECRET =
  process.env.SITE_PASSWORD || process.env.TMDB_TOKEN || "onyxtv-fallback";

/**
 * Sign a stream request so the API route can verify it originated from our server.
 * Token = HMAC-SHA256( "type:tmdbId", secret )
 */
export function signStreamToken(type: string, tmdbId: number): string {
  const payload = `${type}:${tmdbId}`;
  return crypto.createHmac("sha256", SECRET).update(payload).digest("hex");
}

/**
 * Verify that a stream token is valid for the given type + tmdbId.
 */
export function verifyStreamToken(
  type: string,
  tmdbId: number,
  token: string
): boolean {
  const expected = signStreamToken(type, tmdbId);
  if (expected.length !== token.length) return false;
  return crypto.timingSafeEqual(
    Buffer.from(expected, "hex"),
    Buffer.from(token, "hex")
  );
}
